[build]
  # Build command
  command = "npm run build"
  # Output directory
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Node.js version
  NODE_VERSION = "18"