[build]
  # Build command
  command = "CI=false npm run build"
  # Output directory
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  # Disable CI mode to prevent treating warnings as errors
  CI = "false"